[package]
name = "rofi-mode"
version = "0.1.0"
edition = "2021"
rust-version = "1.59.0"
description = "High-level library for creating Rofi plugins and custom modes"
repository = "https://github.com/SabrinaJewson/rofi-mode"
license = "MIT"
keywords = ["rofi", "mode", "plugin"]
categories = ["api-bindings"]

[dependencies]
rofi-plugin-sys = { git = "https://github.com/SabrinaJewson/rofi-plugin-sys.rs" }
bitflags = "1.3.2"
pango = { version = "0.15.10", features = ["v1_46"] }

[workspace]
members = ["examples/basic"]
